# Timestamp: 2025-08-12T19:45:49.585337
# CWD: /u1/khabashy/LoRA-MDM

## git
a077da1893a20744cdf28c87bdbba0d5215ce6e7
M data_loaders/get_data.py
 M data_loaders/humanml/data/dataset.py
 M data_loaders/humanml/scripts/motion_process.py
 M data_loaders/tensors.py
 M diffusion/gaussian_diffusion.py
 M model/mdm.py
 D prepare/download_a2m_datasets.sh
 D prepare/download_glove.sh
 D prepare/download_recognition_models.sh
 D prepare/download_recognition_unconstrained_models.sh
 D prepare/download_smpl_files.sh
 D prepare/download_t2m_evaluators.sh
 D prepare/download_unconstrained_datasets.sh
 M train/train_mdm.py
 M train/training_loop.py
 M utils/model_util.py
?? LoRA_convert.ipynb
?? _manifests/
?? analysis.py
?? data/
?? eval/a2m/
?? eval/eval_humanact12_uestc.py
?? eval/eval_humanml.py
?? ezc3d/
?? humanact12_motion_analysis/
?? lists/
?? moshpp/
?? results/
?? tools/
?? utils/sampler_util.py
origin	https://github.com/haimsaw/LoRA-MDM.git (fetch)
origin	https://github.com/haimsaw/LoRA-MDM.git (push)

## conda env (moshpp37)
Error while loading conda entry point: conda-build (cannot import name 'tarfile' from 'backports' (/opt/anaconda3/lib/python3.11/site-packages/backports/__init__.py))
WARNING conda.plugins.manager:load_entrypoints(114): Error while loading conda entry point: conda-build (cannot import name 'tarfile' from 'backports' (/opt/anaconda3/lib/python3.11/site-packages/backports/__init__.py))
name: moshpp37
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cmake=3.22.1=h1fce559_0
  - expat=2.7.1=h6a678d5_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.52.0=ha637b67_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.5=h7934f7d_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1w=h7f8727e_0
  - pcre2=10.42=hebb0a14_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.7.16=h7a1cb2a_0
  - readline=8.3=hc2a1206_0
  - rhash=1.4.1=h3c74f83_1
  - sqlite=3.50.2=hb25bd0a_1
  - swig=4.3.0=he621ea3_0
  - tk=8.6.14=h993c535_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - body-visualizer==1.1.0
      - c3d==0.5.2
      - chumpy==0.70
      - colour==0.1.5
      - cycler==0.11.0
      - fonttools==4.38.0
      - human-body-prior==2.2.2.0
      - hydra-core==1.3.2
      - importlib-resources==5.12.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - loguru==0.7.3
      - matplotlib==3.5.3
      - numpy==1.21.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - pip==24.0
      - pyopengl==3.1.9
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==26.2.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - setuptools==68.0.0
      - six==1.17.0
      - smplx==0.1.28
      - threadpoolctl==3.1.0
      - torch==1.10.0+cu113
      - torchaudio==0.10.0+cu113
      - torchvision==0.11.0+cu113
      - trimesh==4.4.1
      - typing-extensions==4.7.1
      - wheel==0.42.0
      - zipp==3.15.0
prefix: /u1/khabashy/.conda/envs/moshpp37

## python versions
Python 3.7.16
3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0]
torch 1.10.0+cu113
cuda 11.3
is_cuda_available False
platform Linux-6.8.0-52-generic-x86_64-with-debian-bookworm-sid

## CUDA / Drivers
[error running nvidia-smi] [Errno 8] Exec format error: 'nvidia-smi'
[error running nvcc --version] [Errno 2] No such file or directory: 'nvcc': 'nvcc'